import {
  applyStylesPayloadSchema,
  batchEditPayloadSchema,
  batchEditV2PayloadSchema,
  bindVariablePayloadSchema,
  createComponentPayloadSchema,
  createFramePayloadSchema,
  createInstancePayloadSchema,
  createPagePayloadSchema,
  createRectanglePayloadSchema,
  createTextPayloadSchema,
  createSpecPagePayloadSchema,
  createVariableCollectionPayloadSchema,
  createVariablePayloadSchema,
  deleteNodePayloadSchema,
  duplicateNodePayloadSchema,
  emptyPayloadSchema,
  extractDesignTokensPayloadSchema,
  findNodesPayloadSchema,
  getComponentsPayloadSchema,
  getStylesPayloadSchema,
  getVariablesPayloadSchema,
  getNodePayloadSchema,
  getNodeTreePayloadSchema,
  moveNodePayloadSchema,
  normalizeNamesPayloadSchema,
  renameNodePayloadSchema,
  setImageFillPayloadSchema,
  setInstancePropertiesPayloadSchema,
  setTextPayloadSchema,
  updateNodePropertiesPayloadSchema
} from "@figma-auto/protocol";

export const toolSchemas = {
  ping: emptyPayloadSchema,
  getSessionStatus: emptyPayloadSchema,
  getFile: emptyPayloadSchema,
  getCurrentPage: emptyPayloadSchema,
  getSelection: emptyPayloadSchema,
  listPages: emptyPayloadSchema,
  getNode: getNodePayloadSchema,
  getNodeTree: getNodeTreePayloadSchema,
  findNodes: findNodesPayloadSchema,
  getStyles: getStylesPayloadSchema,
  getComponents: getComponentsPayloadSchema,
  getVariables: getVariablesPayloadSchema,
  renameNode: renameNodePayloadSchema,
  createPage: createPagePayloadSchema,
  createFrame: createFramePayloadSchema,
  createRectangle: createRectanglePayloadSchema,
  createComponent: createComponentPayloadSchema,
  createInstance: createInstancePayloadSchema,
  createText: createTextPayloadSchema,
  duplicateNode: duplicateNodePayloadSchema,
  setInstanceProperties: setInstancePropertiesPayloadSchema,
  setImageFill: setImageFillPayloadSchema,
  setText: setTextPayloadSchema,
  applyStyles: applyStylesPayloadSchema,
  updateNodeProperties: updateNodePropertiesPayloadSchema,
  moveNode: moveNodePayloadSchema,
  deleteNode: deleteNodePayloadSchema,
  batchEdit: batchEditPayloadSchema,
  batchEditV2: batchEditV2PayloadSchema,
  createVariableCollection: createVariableCollectionPayloadSchema,
  createVariable: createVariablePayloadSchema,
  bindVariable: bindVariablePayloadSchema,
  normalizeNames: normalizeNamesPayloadSchema,
  createSpecPage: createSpecPagePayloadSchema,
  extractDesignTokens: extractDesignTokensPayloadSchema
};
