import {
  batchEditPayloadSchema,
  bindVariablePayloadSchema,
  createComponentPayloadSchema,
  createFramePayloadSchema,
  createPagePayloadSchema,
  createTextPayloadSchema,
  createSpecPagePayloadSchema,
  createVariableCollectionPayloadSchema,
  createVariablePayloadSchema,
  deleteNodePayloadSchema,
  emptyPayloadSchema,
  extractDesignTokensPayloadSchema,
  findNodesPayloadSchema,
  getVariablesPayloadSchema,
  getNodePayloadSchema,
  getNodeTreePayloadSchema,
  moveNodePayloadSchema,
  normalizeNamesPayloadSchema,
  renameNodePayloadSchema,
  setTextPayloadSchema
} from "@figma-auto/protocol";

export const toolSchemas = {
  ping: emptyPayloadSchema,
  getFile: emptyPayloadSchema,
  getCurrentPage: emptyPayloadSchema,
  getSelection: emptyPayloadSchema,
  listPages: emptyPayloadSchema,
  getNode: getNodePayloadSchema,
  getNodeTree: getNodeTreePayloadSchema,
  findNodes: findNodesPayloadSchema,
  getVariables: getVariablesPayloadSchema,
  renameNode: renameNodePayloadSchema,
  createPage: createPagePayloadSchema,
  createFrame: createFramePayloadSchema,
  createComponent: createComponentPayloadSchema,
  createText: createTextPayloadSchema,
  setText: setTextPayloadSchema,
  moveNode: moveNodePayloadSchema,
  deleteNode: deleteNodePayloadSchema,
  batchEdit: batchEditPayloadSchema,
  createVariableCollection: createVariableCollectionPayloadSchema,
  createVariable: createVariablePayloadSchema,
  bindVariable: bindVariablePayloadSchema,
  normalizeNames: normalizeNamesPayloadSchema,
  createSpecPage: createSpecPagePayloadSchema,
  extractDesignTokens: extractDesignTokensPayloadSchema
};
